version: '3.7'
services:
  db:
    image: postgres
    restart: always
    container_name: prisma-nestjs
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: prisma-nestjs
    ports:
      - 5432:5432
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
networks:
  internal:
    name: internal
    driver: bridge
